---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jellyfin
  namespace: argocd
spec:
  destination:
    namespace: jellyfin
    server: 'https://kubernetes.default.svc'
  sources:
  - repoURL: 'https://jellyfin.github.io/jellyfin-helm'
    chart: jellyfin
    targetRevision: 2.3.0
    helm:
      valueFiles:
      - $values/base/kubernetes/jellyfin/values.yaml
  - repoURL: 'https://github.com/DawidDe/homelab.git'
    targetRevision: HEAD
    path: base/kubernetes/jellyfin
    ref: values
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
      enabled: true
    syncOptions:
    - CreateNamespace=true
  env:
    - name: DOMAIN
      value: "jellyfin.dawidde.de"