apiVersion: traefik.containo.us/v1alpha1
kind: TraefikService
metadata:
  name: wings-0-service
  namespace: wings
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  weighted:
    services:
      - name: external-ip
        weight: 1
        kind: TraefikService
        servers:
          - url: "http://192.168.178.116:8080"