---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-vault-plugin
  namespace: argocd
spec:
  destination:
    namespace: argocd-vault-plugin
    server: 'https://kubernetes.default.svc'
  sources:
  - repoURL: 'https://github.com/DawidDe/homelab.git'
    targetRevision: HEAD
    path: base/kubernetes/argocd-vault-plugin
    ref: values
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
      enabled: true
    syncOptions:
    - CreateNamespace=true