---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: argocd-vault-plugin-secrets
  namespace: argocd
  annotations:
    argocd.argoproj.io/hook: PreSync
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-secret-store
    kind: ClusterSecretStore
  target:
    name: argocd-vault-plugin-credentials
  data:
  - secretKey: VAULT_ADDR
    remoteRef:
      key: kv/argocd-vault-plugin
      property: vault_addr
  - secretKey: AVP_TYPE
    remoteRef:
      key: kv/argocd-vault-plugin
      property: avp_type
  - secretKey: AVP_AUTH_TYPE
    remoteRef:
      key: kv/argocd-vault-plugin
      property: avp_auth_type
  - secretKey: AVP_ROLE_ID
    remoteRef:
      key: kv/argocd-vault-plugin
      property: avp_role_id
  - secretKey: AVP_SECRET_ID
    remoteRef:
      key: kv/argocd-vault-plugin
      property: avp_secret_id