---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: local-path-provisioner
  namespace: argocd
spec:
  destination:
    namespace: local-path-provisioner
    server: 'https://kubernetes.default.svc'
  sources:
  - repoURL: 'git@github.com:dawidde/kustomize-overlays.git'
    path: apps/local-path-provisioner/overlays/prod
    targetRevision: main
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
      enabled: true
    syncOptions:
    - CreateNamespace=true