---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pelican-panel
  namespace: argocd
spec:
  destination:
    namespace: pelican-panel
    server: 'https://kubernetes.default.svc'
  sources:
  - repoURL: 'https://dawidde.github.io/helm-charts/'
    chart: pelican-panel
    targetRevision: 0.1.18
    helm:
      valueFiles:
      - $values/base/kubernetes/pelican-panel/values.yaml
  - repoURL: 'https://github.com/DawidDe/homelab.git'
    targetRevision: HEAD
    path: base/kubernetes/pelican-panel
    ref: values
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
      enabled: true
    syncOptions:
    - CreateNamespace=true