---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: pelican-panel-certificate
  namespace: pelican-panel
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/sync-wave: "0"
spec:
  secretName: pelican-panel-certificate-secret
  issuerRef:
    name: cloudflare
    kind: ClusterIssuer
  dnsNames:
    - pelicantest.dawidde.de