---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: pelican-panel-ingressroute
  namespace: pelican-panel
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/sync-wave: "1"
spec:
  entryPoints:
    - websecure
  routes:
  - match: Host(`pelicantest.dawidde.de`)
    kind: Rule
    services:
    - name: pelican-panel-service
      port: 80
  tls:
    secretName: pelican-panel-certificate-secret