---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pelican-panel-data-pv
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/sync-wave: "0"
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: pelican-panel-data
  hostPath:
    path: /var/mnt/zfs/pelican-panel/data
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pelican-panel-logs-pv
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/sync-wave: "0"
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: pelican-panel-logs
  hostPath:
    path: /var/mnt/zfs/pelican-panel/logs
    type: DirectoryOrCreate