# Default values for Pelican Panel Helm Chart
# This is a YAML-formatted file.

general:
  fullnameOverride: ""
  nameOverride: ""
  domain: "https://pelicantest.dawidde.de"
  caddy:
    admin: "off"
    # The IP of your reverse proxy
    trusted_proxies: 10.110.192.233
    # When leaving these settings empty its using the standard settings
    upload_max_filesize: ''
    post_max_size: ''

image:
  # Container image repository for Pelican Panel.
  repository: ghcr.io/pelican-dev/panel
  # Pelican Panel container image tag. Leave empty to automatically use the Chart's app version.
  tag: ""
  # Image pull policy (Alyways, IfNotPresent or Never).
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

volumes:
  data:
    enabled: true
    accessMode: ReadWriteOnce
    size: 1Gi
    storageClassName: 'pelican-panel-data'
  logs:
    enabled: true
    accessMode: ReadWriteOnce
    size: 1Gi
    storageClassName: 'pelican-panel-logs'