---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: home-assistant-certificate
  namespace: home-assistant
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/sync-wave: "1"
spec:
  secretName: home-assistant-certificate-secret
  issuerRef:
    name: cloudflare
    kind: ClusterIssuer
  dnsNames:
    - home.dawidde.de